name: Generate signed AAB (prd-release)

env:
  main_project_module: app

on: workflow_dispatch

jobs:
  aab_prod_release_build:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_FILE_PASSWORD: ${{ secrets.KEYSTORE_FILE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y_%m_%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execution permission for gradlew
        run: chmod +x ./gradlew

      - name: Decode keystore base64
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > /tmp/keystore.jks

      - name: Build signed AAB prd release
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Build APK prd release
        run: ./gradlew assembleRelease

      - name: Upload AAB artifact - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}_${{ env.repository_name }}_prod_aab
          path: ${{ env.main_project_module }}/build/outputs/bundle/prdRelease/

      - name: Upload APK artifact - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}_${{ env.repository_name }}_prod_apk
          path: ${{ env.main_project_module }}/build/outputs/apk/prd/release/