name: Generate APK (dev-debug)

on: workflow_dispatch

jobs:
  apk_dev_debug_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y_%m_%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execution permission for gradlew
        run: chmod +x ./gradlew

      - name: Build gradle project
        run: ./gradlew build

      - name: Build APK dev debug
        run: ./gradlew :app:packageDevDebugUniversalApk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}_${{ env.repository_name }}_dev_apk
          path: app/build/outputs/apk_from_bundle/devDebug
