name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  main_project_module: app

on:
  # Allows to run this workflow manually from Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execution permission for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew clean testDevDebugUnitTest

      - name: Build gradle project
        run: ./gradlew build

      - name: Build APK dev debug
        run: ./gradlew assembleDebug