name: Run test

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execution permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDevDebugUnitTest